apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaksdum-1835"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaksdum-1835"
  template:
    metadata:
      labels:
        app: "myaksdum-1835"
    spec:
      containers:
        - name: "myaksdum-1835"
          image: "crappdum.azurecr.io/myaksdum"
          ports:
          - containerPort: 80