apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksdum-6c4a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksdum-6c4a"
  template:
    metadata:
      labels:
        app: "aksdum-6c4a"
    spec:
      containers:
        - name: "aksdum-6c4a"
          image: "acrdum.azurecr.io/aksdum"
          ports:
          - containerPort: 80