apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksdum-1129"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksdum-1129"
  template:
    metadata:
      labels:
        app: "aksdum-1129"
    spec:
      containers:
        - name: "aksdum-1129"
          image: "craksdum.azurecr.io/aksdum"
          ports:
          - containerPort: 80